server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/personal_blog_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  data:
    redis:
      port: 6379
      host: localhost

logging:
  charset:
    console: UTF-8
  level:
    com.blog: debug
